const directoryActionTypes = {
	FETCH_DIRECTORY_SECTIONS_START: 'FETCH_DIRECTORY_SECTIONS_START',
	FETCH_DIRECTORY_SECTIONS_SUCCESS: 'FETCH_DIRECTORY_SECTIONS_SUCCESS',
	FETCH_DIRECTORY_SECTIONS_FAILURE: 'FETCH_DIRECTORY_SECTIONS_FAILURE',
}
export default directoryActionTypes
